// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHTd5rJds1pnoBhKGC05pkK9FzKYLqPMg',
    appId: '1:389543289869:web:e919201f95b277487de144',
    messagingSenderId: '389543289869',
    projectId: 'xpenso-4b3e3',
    authDomain: 'xpenso-4b3e3.firebaseapp.com',
    storageBucket: 'xpenso-4b3e3.firebasestorage.app',
    measurementId: 'G-MND04VREV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcxXmLpAeoky7O0Sx74wux5PMTlZcUZRA',
    appId: '1:389543289869:android:0d647c0141d1e4de7de144',
    messagingSenderId: '389543289869',
    projectId: 'xpenso-4b3e3',
    storageBucket: 'xpenso-4b3e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnNWLroJnrhwKHxvPsWFjKX3YrfSdJSa4',
    appId: '1:389543289869:ios:21774b7220e6421b7de144',
    messagingSenderId: '389543289869',
    projectId: 'xpenso-4b3e3',
    storageBucket: 'xpenso-4b3e3.firebasestorage.app',
    iosBundleId: 'com.example.xpenso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnNWLroJnrhwKHxvPsWFjKX3YrfSdJSa4',
    appId: '1:389543289869:ios:21774b7220e6421b7de144',
    messagingSenderId: '389543289869',
    projectId: 'xpenso-4b3e3',
    storageBucket: 'xpenso-4b3e3.firebasestorage.app',
    iosBundleId: 'com.example.xpenso',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHTd5rJds1pnoBhKGC05pkK9FzKYLqPMg',
    appId: '1:389543289869:web:2cbce6c80609cfed7de144',
    messagingSenderId: '389543289869',
    projectId: 'xpenso-4b3e3',
    authDomain: 'xpenso-4b3e3.firebaseapp.com',
    storageBucket: 'xpenso-4b3e3.firebasestorage.app',
    measurementId: 'G-PF3HCPS9KP',
  );
}
